---
website_navigation_task:
  description: Navigate the website starting at {url} to locate all pages that contain
    relevant {data_type} content. Identify and list these pages for further data extraction.
  expected_output: A comprehensive list of URLs pointing to pages containing the specified
    {data_type} data.
  async_execution: false
  agent: navigator
data_extraction_task:
  description: Using the list of pages from website_navigation_task, extract the {data_type}
    details by employing dynamic and static scraping strategies. Utilize tools like
    ScrapeWebsiteTool, SeleniumScrapingTool, or ScrapeElementFromWebsiteTool based
    on the page requirements.
  expected_output: Aggregated raw data containing the {data_type} information from
    all designated pages.
  async_execution: false
  agent: scraper
  context:
  - website_navigation_task
data_validation_task:
  description: Process and clean the raw data obtained from data_extraction_task.
    Validate the data and structure it into formats such as JSON or CSV, ensuring
    consistency and accuracy.
  expected_output: Cleaned and structured dataset with the {data_type} details, ready
    for storage or further analysis.
  async_execution: false
  agent: validator
  context:
  - data_extraction_task
data_storage_task:
  description: Store the validated and structured data to the storage destination
    defined by {storage_params}. Ensure secure and efficient saving for future retrieval
    or analysis.
  expected_output: Confirmation of the data being stored at {storage_params} with
    correct file formats and structure.
  async_execution: false
  agent: storage
  context:
  - data_validation_task
task_scheduling_task:
  description: Configure the execution schedule for the web scraping operation. Establish
    on-demand and periodic triggers based on {frequency} to ensure that the scraping,
    extraction, and storage tasks run reliably over time.
  expected_output: A scheduling setup (e.g., cron job or similar) that confirms the
    automated execution of the tasks at the specified frequency.
  async_execution: false
  agent: scheduler
